//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KumysWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawMaterials
    {
        public int RawMaterialID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
